$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0
$repoRoot = Split-Path -Parent $PSScriptRoot
$scriptsRoot = Join-Path $repoRoot 'scripts'
. (Join-Path $scriptsRoot 'CodexDispatchRoutingResumeOrchestrator.Common.ps1')
$publicPath = Join-Path $scriptsRoot 'Invoke-CodexDispatchRoutingResume.ps1'
$script:passed = 0
function Pass { param([string]$Name) $script:passed++; Write-Host "PASS $script:passed`: $Name" }
function Assert-True { param([bool]$Value,[string]$Name) if(-not $Value){throw "ASSERT TRUE: $Name"};Pass $Name }
function Assert-Equal { param($Actual,$Expected,[string]$Name) Assert-True ((@($Actual)-join '|') -ceq (@($Expected)-join '|')) $Name }
function Assert-Throws { param([scriptblock]$Action,[string]$Name) try {& $Action;throw 'expected throw'}catch{if($_.Exception.Message -eq 'expected throw'){throw};Pass $Name} }
function New-State {
 param([string]$Phase='routing',[string]$Status='needs_input')
 [pscustomobject][ordered]@{version=1;dispatchId='11111111-1111-1111-1111-111111111111';revision=[int64]5;createdAtUtc='2026-01-01T00:00:00.0000000Z';updatedAtUtc='2026-01-01T00:00:00.0000000Z';phase=$Phase;status=$Status;task='fix README typo';projectRepository=$null;threadId=$null;report='old report';question='Which project?';context='prior context';options=[string[]]@('owner/oss','owner/private');diagnostic=''}
}
function Copy-State { param($State) $copy=[ordered]@{};foreach($name in $State.PSObject.Properties.Name){$copy[$name]=if($name -eq 'options'){[string[]]@($State.options)}else{$State.$name}};[pscustomobject]$copy }
function Fast-Result { param([string]$Status='strong',$Repository='owner/oss') [pscustomobject][ordered]@{version=1;status=$Status;topScore=1;lead=1;selectedProject=$(if($Status -eq 'strong'){[pscustomobject][ordered]@{name='x';localPath='C:\router-local-path';githubRepository=$Repository;score=1;matchedSignals=,([object[]]@())}}else{$null});candidates=,([object[]]@())} }
function Slow-Result { param([string]$Status='routed') [pscustomobject][ordered]@{version=1;status=$Status;selectedProject=$(if($Status -eq 'routed'){[pscustomobject][ordered]@{name='x';localPath='C:\router-local-path';githubRepository='owner/private'}}else{$null});confidence='';reason=$(if($Status -eq 'no_match'){'MODEL-REASON'}else{''});question=$(if($Status -eq 'needs_input'){'MODEL-QUESTION'}else{''});options=$(if($Status -eq 'needs_input'){[string[]]@('owner/oss','owner/private')}else{,([string[]]@())})} }
function Worker-Result { param([string]$Status='completed',$Thread='22222222-2222-2222-2222-222222222222') [pscustomobject][ordered]@{version=1;status=$Status;project=[pscustomobject]@{name='untrusted';localPath='C:\worker-ignored';githubRepository='owner/ignored'};threadId=$Thread;report=$(if($Status -eq 'completed'){'completed report'}elseif($Status -eq 'needs_input'){'worker report'}else{''});question=$(if($Status -eq 'needs_input'){'worker question'}else{''});context=$(if($Status -eq 'needs_input'){'worker context'}else{''});options=$(if($Status -eq 'needs_input'){[string[]]@('A','B')}else{,([string[]]@())});exitCode=$(if($Status -eq 'failed'){1}else{0});diagnostic=$(if($Status -eq 'failed'){'RAW-WORKER-FAILURE C:\private'}else{''})} }
function New-Fixture {
 param($State,[string]$FastMode='strong',$FastRepository='owner/oss',[string]$SlowMode='routed',[string]$WorkerMode='completed',[string]$PublisherMode='updated')
 $ctx=[pscustomobject]@{State=$State;FastMode=$FastMode;FastRepository=$FastRepository;SlowMode=$SlowMode;WorkerMode=$WorkerMode;PublisherMode=$PublisherMode;Events=[Collections.Generic.List[string]]::new();Updates=0;Gets=0;FailUpdateAt=0;FailGetAt=0;FastRequest=$null;SlowRequest=$null;WorkerRequest=$null;PublisherRequest=$null;FastEnv=$null;SlowEnv=$null;WorkerEnv=$null;PublisherEnv=$null;RunningState=$null}
 $fastValue=if($FastMode -notin @('throw','malformed')){Fast-Result $FastMode $FastRepository}else{$null}
 $slowValue=if($SlowMode -notin @('throw','malformed')){Slow-Result $SlowMode}else{$null}
 $workerValue=if($WorkerMode -eq 'failednull'){Worker-Result failed $null}elseif($WorkerMode -eq 'failedinvalid'){Worker-Result failed bad}elseif($WorkerMode -notin @('throw','malformed')){Worker-Result $WorkerMode}else{$null}
 $get={param($request)[void]$ctx.Events.Add('Get');$ctx.Gets++;if($ctx.FailGetAt -eq $ctx.Gets){throw 'RAW-STATE-READ C:\private'};return $ctx.State}.GetNewClosure()
 $update={param($request)[void]$ctx.Events.Add('Update');$ctx.Updates++;if($ctx.FailUpdateAt -eq $ctx.Updates){throw 'RAW-STATE-WRITE C:\private'};if([int64]$request.ExpectedRevision -ne [int64]$ctx.State.revision){throw 'revision mismatch'};$values=[ordered]@{};foreach($name in $ctx.State.PSObject.Properties.Name){$values[$name]=if($name -eq 'options'){[string[]]@($ctx.State.options)}else{$ctx.State.$name}};$next=[pscustomobject]$values;$next.revision=[int64]$ctx.State.revision+1;$next.phase=[string]$request.Phase;$next.status=[string]$request.Status;foreach($pair in @(@('ProjectRepository','projectRepository'),@('ThreadId','threadId'),@('Report','report'),@('Question','question'),@('Context','context'),@('Options','options'),@('Diagnostic','diagnostic'))){if($request.Contains($pair[0])){if($pair[0] -eq 'Options'){$optionValues=[string[]]@($request[$pair[0]]);$next.options=$optionValues}else{$next.($pair[1])=$request[$pair[0]]}}};$ctx.State=$next;return $ctx.State}.GetNewClosure()
 $fast={param($request)[void]$ctx.Events.Add('Fast');$ctx.FastRequest=$request;$ctx.FastEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);if($ctx.FastMode -eq 'throw'){throw 'RAW-FAST C:\private'};if($ctx.FastMode -eq 'malformed'){return [pscustomobject]@{status='bad'}};return $fastValue}.GetNewClosure()
 $slow={param($request)[void]$ctx.Events.Add('Slow');$ctx.SlowRequest=$request;$ctx.SlowEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);if($ctx.SlowMode -eq 'throw'){throw 'RAW-SLOW C:\private'};if($ctx.SlowMode -eq 'malformed'){return [pscustomobject]@{status='bad'}};return $slowValue}.GetNewClosure()
 $worker={param($request)[void]$ctx.Events.Add('Worker');$ctx.WorkerRequest=$request;$ctx.WorkerEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);$ctx.RunningState=$ctx.State;if($ctx.WorkerMode -eq 'throw'){throw 'RAW-WORKER C:\private'};if($ctx.WorkerMode -eq 'malformed'){return [pscustomobject]@{status='bad'}};return $workerValue}.GetNewClosure()
 $publisher={param($request)[void]$ctx.Events.Add('Publisher');$ctx.PublisherRequest=$request;$ctx.PublisherEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);if($ctx.PublisherMode -eq 'throw'){throw 'RAW-PUBLISHER C:\private'};$action=$ctx.PublisherMode;$id=[string]$ctx.State.dispatchId;$revision=[int64]$ctx.State.revision;$number=[int64]$request.IssueNumber;if($action -eq 'wrongdispatch'){$action='updated';$id='33333333-3333-3333-3333-333333333333'}elseif($action -eq 'wrongrevision'){$action='updated';$revision++}elseif($action -eq 'wrongissue'){$action='updated';$number++};if($action -eq 'malformed'){return [pscustomobject]@{action='updated'}};return [pscustomobject][ordered]@{version=1;action=$action;dispatchId=$id;revision=$revision;repository='owner/control';issueNumber=$number;issueUrl='https://example.test/42'}}.GetNewClosure()
 return [pscustomobject]@{Dependencies=[pscustomobject][ordered]@{GetState=$get;UpdateState=$update;FastRouter=$fast;SlowRouter=$slow;Worker=$worker;Publisher=$publisher};Context=$ctx}
}
function Invoke-Fake { param($Fixture,[string]$Answer='owner/oss') Invoke-CodexDispatchRoutingResumeOrchestratorInternal -DispatchId '11111111-1111-1111-1111-111111111111' -Answer $Answer -IssueNumber 42 -ConfigPath '' -Dependencies $Fixture.Dependencies }
function Assert-NoCredential {param($Environment,[string]$Name)foreach($variable in @('CODEX_DISPATCH_GITHUB_TOKEN','GH_TOKEN','GITHUB_TOKEN')){Assert-True (-not $Environment.Contains($variable)) "$Name hides $variable"}}

$caseRoot=Join-Path ([IO.Path]::GetTempPath()) ('routing-resume-test-'+[guid]::NewGuid().ToString('N'));[void](New-Item -ItemType Directory $caseRoot);[IO.File]::WriteAllText((Join-Path $caseRoot 'project-index.json'),'{}',[Text.UTF8Encoding]::new($false));$saved=Get-CodexDispatchOrchestratorCredentialSnapshot
Push-Location $caseRoot
try {
 Remove-CodexDispatchOrchestratorCredentials
 foreach($answer in @('', ' ', ('x'*16385))){Assert-Throws {Assert-RoutingResumeInput '11111111-1111-1111-1111-111111111111' $answer 42} 'Answer rejected'};Assert-RoutingResumeInput '11111111-1111-1111-1111-111111111111' ('x'*16384) 42;Pass 'Answer boundary';Assert-Throws {Assert-RoutingResumeInput bad x 42} 'DispatchId rejected';Assert-Throws {Assert-RoutingResumeInput '11111111-1111-1111-1111-111111111111' x 0} 'IssueNumber rejected'
 foreach($pair in @(@('routing','pending'),@('routing','running'),@('worker','running'),@('worker','needs_input'),@('worker','completed'),@('worker','failed'))){$f=New-Fixture (New-State $pair[0] $pair[1]);Assert-Throws {Invoke-Fake $f} "reject $($pair -join '/')";Assert-Equal $f.Context.Events.Count 1 "no Router after reject $($pair -join '/')"}
 $f=New-Fixture (New-State);$out=Invoke-Fake $f 'owner/oss';Assert-Equal $f.Context.Events @('Get','Update','Get','Fast','Update','Get','Worker','Update','Get','Publisher') 'direct call order';Assert-Equal $f.Context.FastRequest.Task 'owner/oss' 'Fast exact Answer';Assert-Equal $f.Context.WorkerRequest.Task 'fix README typo' 'Worker original task';Assert-True (-not $f.Context.WorkerRequest.Contains('Answer')) 'Worker no Answer key';Assert-Equal $f.Context.WorkerRequest.ProjectRepository 'owner/oss' 'Worker selected repo only';Assert-Equal $f.Context.RunningState.phase worker 'worker running before Worker';Assert-Equal $f.Context.RunningState.status running 'worker running status';Assert-Equal $f.Context.RunningState.threadId $null 'worker running null thread';Assert-Equal $f.Context.RunningState.report '' 'worker running fields clear';Assert-Equal $out.revision 8 'final revision';Assert-True ($out.PSObject.Properties.Name -notcontains 'threadId') 'public hides thread';Assert-Equal $f.Context.State.task 'fix README typo' 'immutable task';Assert-True (-not ((ConvertTo-Json $f.Context.State -Depth 8).Contains('prior context'))) 'envelope not persisted'
 $f=New-Fixture (New-State) -FastMode ambiguous -SlowMode routed;$out=Invoke-Fake $f 'the second one';Assert-Equal $f.Context.Events @('Get','Update','Get','Fast','Slow','Update','Get','Worker','Update','Get','Publisher') 'Slow call order';$envelope=ConvertFrom-Json $f.Context.SlowRequest.Task;Assert-Equal @($envelope.PSObject.Properties.Name) @('originalTask','routingClarification') 'envelope top order';Assert-Equal @($envelope.routingClarification.PSObject.Properties.Name) @('question','context','options','answer') 'envelope nested order';Assert-Equal $envelope.routingClarification.answer 'the second one' 'Slow envelope Answer';Assert-Equal $envelope.routingClarification.options @('owner/oss','owner/private') 'Slow envelope options';Assert-Equal $f.Context.WorkerRequest.Task 'fix README typo' 'envelope excluded Worker';Assert-Equal $out.projectRepository 'owner/private' 'Slow selected repository';Assert-True (-not $f.Context.WorkerRequest.ProjectRepository.Contains('C:\')) 'router local path not authority'
 foreach($mode in @('strong-null','ambiguous','no_match','disabled')){$fast=if($mode -eq 'strong-null'){'strong'}else{$mode};$repo=if($mode -eq 'strong-null'){$null}else{'owner/oss'};$f=New-Fixture (New-State) -FastMode $fast -FastRepository $repo;$out=Invoke-Fake $f;Assert-True ($f.Context.Events -contains 'Slow') "Fast $mode invokes Slow"}
 foreach($mode in @('throw','malformed')){$f=New-Fixture (New-State) -FastMode $mode;$out=Invoke-Fake $f;Assert-Equal $out.phase routing "Fast $mode routing";Assert-Equal $out.status needs_input "Fast $mode needs input";Assert-True (-not ($f.Context.Events -contains 'Slow')) "Fast $mode no Slow";Assert-Equal $out.context 'A Router component failed or returned an invalid contract.' "Fast $mode fixed context"}
 foreach($mode in @('needs_input','no_match','disabled','throw','malformed')){$f=New-Fixture (New-State) -FastMode ambiguous -SlowMode $mode;$out=Invoke-Fake $f;Assert-Equal $out.phase routing "Slow $mode routing";Assert-Equal $out.status needs_input "Slow $mode needs input";Assert-True (-not ($f.Context.Events -contains 'Worker')) "Slow $mode no Worker"}
 $f=New-Fixture (New-State) -FastMode ambiguous -SlowMode needs_input;$out=Invoke-Fake $f;Assert-Equal $out.report 'Routing still needs a project selection.' 'Slow fixed report';Assert-Equal $out.question 'Which project did you mean?' 'Slow fixed question';Assert-Equal $out.context 'Slow Router still found multiple plausible projects.' 'Slow fixed context';Assert-Equal $out.options @('owner/oss','owner/private') 'Slow validated options';Assert-True (-not ((ConvertTo-Json $out -Depth 8).Contains('MODEL-QUESTION'))) 'Slow model text not persisted'
 foreach($mode in @('completed','needs_input','failed','failednull','failedinvalid','throw','malformed')){$f=New-Fixture (New-State) -WorkerMode $mode;$out=Invoke-Fake $f;if($mode -eq 'completed'){Assert-Equal $f.Context.State.status completed 'completed State';Assert-Equal $f.Context.State.threadId '22222222-2222-2222-2222-222222222222' 'completed thread'}elseif($mode -eq 'needs_input'){Assert-Equal $f.Context.State.status needs_input 'needs input State';Assert-Equal $f.Context.State.threadId '22222222-2222-2222-2222-222222222222' 'needs input thread';Assert-Equal $f.Context.State.options @('A','B') 'needs input shape'}else{Assert-Equal $f.Context.State.status failed "Worker $mode failed";if($mode -in @('failednull','failedinvalid','throw','malformed')){Assert-Equal $f.Context.State.threadId $null "Worker $mode null thread"}}}
 foreach($failure in @(@('FailUpdateAt',1,'first write'),@('FailGetAt',2,'routing readback'),@('FailUpdateAt',2,'worker write'),@('FailGetAt',3,'worker readback'),@('FailUpdateAt',3,'final write'),@('FailGetAt',4,'final readback'))){$f=New-Fixture (New-State);$f.Context.($failure[0])=$failure[1];Assert-Throws {Invoke-Fake $f} "State failure $($failure[2])";if($failure[1] -le 1 -or $failure[2] -eq 'routing readback'){Assert-True (-not ($f.Context.Events -contains 'Fast')) "fail stop before Router $($failure[2])"};if($failure[1] -le 2 -or $failure[2] -eq 'worker readback'){Assert-True (-not ($f.Context.Events -contains 'Worker')) "fail stop before Worker $($failure[2])"};Assert-True (-not ($f.Context.Events -contains 'Publisher')) "fail stop no Publisher $($failure[2])"}
 foreach($mode in @('updated','noop','created','wrongdispatch','wrongrevision','wrongissue','malformed','throw')){$f=New-Fixture (New-State) -PublisherMode $mode;$out=Invoke-Fake $f;if($mode -in @('updated','noop')){Assert-Equal $out.issuePublication $mode "Publisher $mode success"}else{Assert-Equal $out.issuePublication failed "Publisher $mode failed";Assert-Equal $out.issueNumber $null "Publisher $mode null number";Assert-Equal $out.issueUrl $null "Publisher $mode null url";Assert-Equal $out.projectionDiagnostic 'Issue publication failed.' "Publisher $mode fixed diagnostic"};Assert-Equal $f.Context.State.status completed "Publisher $mode preserves State"}
 $before=Get-CodexDispatchOrchestratorCredentialSnapshot;[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN','DEDICATED',[EnvironmentVariableTarget]::Process);Set-CodexDispatchOrchestratorEmptyEnvironmentVariable -Name 'GH_TOKEN';[Environment]::SetEnvironmentVariable('GITHUB_TOKEN','GENERAL',[EnvironmentVariableTarget]::Process);$expected=Get-CodexDispatchOrchestratorCredentialSnapshot;try{foreach($mode in @('success','fast','slow','worker','publisher','state')){$f=New-Fixture (New-State);if($mode -eq 'fast'){$f.Context.FastMode='throw'}elseif($mode -eq 'slow'){$f.Context.FastMode='ambiguous';$f.Context.SlowMode='throw'}elseif($mode -eq 'worker'){$f.Context.WorkerMode='throw'}elseif($mode -eq 'publisher'){$f.Context.PublisherMode='throw'}elseif($mode -eq 'state'){$f.Context.FailUpdateAt=1};try{Invoke-Fake $f|Out-Null}catch{};foreach($environment in @($f.Context.FastEnv,$f.Context.SlowEnv,$f.Context.WorkerEnv)){if($null -ne $environment){Assert-NoCredential $environment "$mode dependency"}};if($null -ne $f.Context.PublisherEnv){Assert-Equal $f.Context.PublisherEnv['CODEX_DISPATCH_GITHUB_TOKEN'] 'DEDICATED' "$mode Publisher dedicated";Assert-True (-not $f.Context.PublisherEnv.Contains('GH_TOKEN')) "$mode Publisher GH absent";Assert-True (-not $f.Context.PublisherEnv.Contains('GITHUB_TOKEN')) "$mode Publisher GitHub absent"};$snapshot=Get-CodexDispatchOrchestratorCredentialSnapshot;foreach($record in $expected){$current=@($snapshot|Where-Object{$_.name -ceq $record.name})[0];Assert-Equal $current.exists $record.exists "$mode restore exists $($record.name)";Assert-Equal $current.value $record.value "$mode restore value $($record.name)"}}}finally{Restore-CodexDispatchOrchestratorCredentials -Snapshot $before}
 $tokens=$null;$errors=$null;$ast=[System.Management.Automation.Language.Parser]::ParseFile($publicPath,[ref]$tokens,[ref]$errors);Assert-Equal $errors.Count 0 'public parser';Assert-Equal @($ast.ParamBlock.Parameters|ForEach-Object{$_.Name.VariablePath.UserPath}) @('DispatchId','Answer','IssueNumber','ConfigPath') 'public surface';$text=[IO.File]::ReadAllText($publicPath);foreach($name in @('Task','ProjectRepository','ThreadId','IndexPath','Token')){Assert-True (-not $text.Contains($name)) "public omits $name"}
} finally { Pop-Location;Restore-CodexDispatchOrchestratorCredentials -Snapshot $saved;Remove-Item -LiteralPath $caseRoot -Recurse -Force -ErrorAction SilentlyContinue }
Write-Host "ALL PASS $script:passed"
