$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0

$repoRoot = Split-Path -Parent $PSScriptRoot
$scriptsRoot = Join-Path $repoRoot 'scripts'
. (Join-Path $scriptsRoot 'CodexDispatchResumeOrchestrator.Common.ps1')
$publicPath = Join-Path $scriptsRoot 'Invoke-CodexDispatchResume.ps1'
$newStatePath = Join-Path $scriptsRoot 'New-CodexDispatchState.ps1'
$getStatePath = Join-Path $scriptsRoot 'Get-CodexDispatchState.ps1'
$updateStatePath = Join-Path $scriptsRoot 'Update-CodexDispatchState.ps1'

$testCount = 76; $script:passed = 0
function Assert-True { param([bool]$Condition,[string]$Message) if (-not $Condition) { throw "ASSERT TRUE: $Message" } }
function Assert-Equal { param($Actual,$Expected,[string]$Message) if ((@($Actual) -join '|') -cne (@($Expected) -join '|')) { throw "ASSERT EQUAL: $Message" } }
function Assert-Throws { param([scriptblock]$Action,[string]$Text,[string]$Message) try { & $Action; throw "ASSERT THROW: $Message" } catch { Assert-True $_.Exception.Message.Contains($Text) $Message } }
function Pass { param([string]$Name) $script:passed++; Write-Host "PASS $script:passed/$testCount`: $Name" }
function Assert-EnvironmentSnapshot { param([object[]]$Expected,[string]$Message)
 $actual=Get-CodexDispatchOrchestratorCredentialSnapshot
 foreach($record in $Expected){$current=@($actual|Where-Object {[string]$_.name -ceq [string]$record.name})[0];Assert-Equal $current.exists $record.exists "$Message exists $($record.name)";Assert-Equal $current.value $record.value "$Message value $($record.name)"}
}
function New-Case {
 param([string]$Root,[string]$Name)
 $dir=Join-Path $Root $Name; $workspace=Join-Path $dir 'workspace'; $state=Join-Path $dir 'state'
 [void](New-Item -ItemType Directory -Force -Path $workspace,$state)
 $config=Join-Path $dir 'config.local.json'
 $doc=[ordered]@{version=1;workspace=[ordered]@{root=$workspace;scanDepth=1;allowReparsePoints=$false};runtime=[ordered]@{stateDirectory=$state};controlPlane=[ordered]@{provider='github';repository='example/control';defaultBranch='main'};routing=[ordered]@{fast=[ordered]@{enabled=$true};slow=[ordered]@{enabled=$true}};codex=[ordered]@{command='codex';workerSandbox='workspace-write';routerSandbox='read-only';approvalPolicy='never'};privacy=[ordered]@{exposeLocalPathsInIssues=$false;exposeThreadIdsInIssues=$false;includeOriginalTaskInIssues=$false};safety=[ordered]@{restrictToWorkspaceRoot=$true;requireExplicitAuthorizationFor=@('push','deploy')}}
 [IO.File]::WriteAllText($config,(ConvertTo-Json $doc -Depth 8),[Text.UTF8Encoding]::new($false))
 [IO.File]::WriteAllText((Join-Path $dir 'project-index.json'),'{"version":1,"projects":[]}',[Text.UTF8Encoding]::new($false))
 [pscustomobject]@{Root=$dir;Config=$config;State=$state}
}
function New-ResumeState {
 param($Case,[string]$Phase='worker',[string]$Status='needs_input')
 $s=& $newStatePath -Task 'immutable task' -ConfigPath $Case.Config
 if ($Phase -ceq 'worker' -and $Status -ceq 'needs_input') {
  & $updateStatePath -DispatchId $s.dispatchId -ExpectedRevision $s.revision -Phase routing -Status running -ConfigPath $Case.Config | Out-Null
  $s=& $getStatePath -DispatchId $s.dispatchId -ConfigPath $Case.Config
  & $updateStatePath -DispatchId $s.dispatchId -ExpectedRevision $s.revision -Phase worker -Status running -ProjectRepository owner/project -ConfigPath $Case.Config | Out-Null
  $s=& $getStatePath -DispatchId $s.dispatchId -ConfigPath $Case.Config
  & $updateStatePath -DispatchId $s.dispatchId -ExpectedRevision $s.revision -Phase worker -Status needs_input -ProjectRepository owner/project -ThreadId '11111111-1111-1111-1111-111111111111' -Report old -Question oldq -Context oldc -Options @('A','B') -ConfigPath $Case.Config | Out-Null
 } else { & $updateStatePath -DispatchId $s.dispatchId -ExpectedRevision $s.revision -Phase $Phase -Status $Status -Report route -Question q -Context c -Options @('A','B') -ConfigPath $Case.Config | Out-Null }
 return (& $getStatePath -DispatchId $s.dispatchId -ConfigPath $Case.Config)
}
function New-WorkerResult { param([string]$Status='completed',[string]$ThreadId='11111111-1111-1111-1111-111111111111',[string]$Diagnostic='failure')
 $options=[string[]]@(); if($Status -eq 'needs_input'){$options=[string[]]@('A','B')}
 [pscustomobject][ordered]@{version=1;status=$Status;project=[pscustomobject]@{name='untrusted';localPath='C:\bad';githubRepository='evil/project'};threadId=$ThreadId;report=if($Status -eq 'completed'){'done'}elseif($Status -eq 'needs_input'){'again'}else{''};question=if($Status -eq 'needs_input'){'choose?'}else{''};context=if($Status -eq 'needs_input'){'context'}else{''};options=$options;exitCode=if($Status -eq 'failed'){1}else{0};diagnostic=if($Status -eq 'failed'){$Diagnostic}else{''}}
}
function New-Fixture { param($Case,[string]$Mode='completed',[string]$Publish='updated')
 $c=[pscustomobject]@{WorkerCalls=0;PublisherCalls=0;Updates=0;FailUpdate=0;Mode=$Mode;Publish=$Publish;WorkerRequest=$null;PublisherRequest=$null;WorkerState=$null;PublisherState=$null;WorkerEnv=$null;PublisherEnv=$null}
 $get={param($r) & $getStatePath @r}.GetNewClosure(); $update={param($r) $c.Updates++; if($c.FailUpdate -eq $c.Updates){throw 'state failure C:\secret'}; & $updateStatePath @r}.GetNewClosure()
 $worker={param($r) $c.WorkerCalls++;$c.WorkerRequest=$r;$c.WorkerEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);$c.WorkerState=& $getStatePath -DispatchId $c.DispatchId -ConfigPath $Case.Config;if($c.Mode -eq 'throw'){throw ('worker '+$r.Answer+' C:\private\secret.txt '+$r.ThreadId+' 22222222-2222-2222-2222-222222222222 CREDENTIAL-SECRET-6C2A')};if($c.Mode -eq 'malformed'){return [pscustomobject]@{status='failed'}};$diagnostic=if($c.Mode -eq 'secretfailed'){'STRUCTURED-SECRET-6C2A C:\private\secret.txt 22222222-2222-2222-2222-222222222222'}else{'failure'};$status=if($c.Mode -in @('secretfailed','nullfailed','wrongthread')){'failed'}else{$c.Mode};New-WorkerResult -Status $status -Diagnostic $diagnostic -ThreadId $(if($c.Mode -eq 'nullfailed'){$null}elseif($c.Mode -eq 'wrongthread'){'22222222-2222-2222-2222-222222222222'}else{'11111111-1111-1111-1111-111111111111'})}.GetNewClosure()
 $publisher={param($r)$c.PublisherCalls++;$c.PublisherRequest=$r;$c.PublisherEnv=[Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process);$c.PublisherState=& $getStatePath -DispatchId $r.DispatchId -ConfigPath $Case.Config;if($c.Publish -eq 'throw'){throw 'PROJECTION-SECRET-6C2A C:\private\secret.txt 22222222-2222-2222-2222-222222222222 CREDENTIAL-SECRET-6C2A'};$dispatch=if($c.Publish -eq 'wrongdispatch'){'22222222-2222-2222-2222-222222222222'}else{$r.DispatchId};$revision=if($c.Publish -eq 'wrongrevision'){[int64]$c.PublisherState.revision+1}else{[int64]$c.PublisherState.revision};$number=if($c.Publish -eq 'wrongissue'){[int64]43}else{[int64]$r.IssueNumber};$action=if($c.Publish -in @('wrongdispatch','wrongrevision','wrongissue')){'updated'}else{$c.Publish};[pscustomobject][ordered]@{version=1;action=$action;dispatchId=$dispatch;revision=$revision;repository='example/control';issueNumber=$number;issueUrl='https://example.test/42'}}.GetNewClosure()
 [pscustomobject]@{Dependencies=[pscustomobject][ordered]@{GetState=$get;UpdateState=$update;ResumeWorker=$worker;Publisher=$publisher};Context=$c}
}
function Invoke-Resume { param($Case,$Fixture,$State,[string]$Answer=' answer ' ,[Int64]$Issue=42) $Fixture.Context | Add-Member -NotePropertyName DispatchId -NotePropertyValue $State.dispatchId -Force;Push-Location $Case.Root;try{Invoke-CodexDispatchResumeOrchestratorInternal -DispatchId $State.dispatchId -Answer $Answer -IssueNumber $Issue -ConfigPath $Case.Config -Dependencies $Fixture.Dependencies}finally{Pop-Location} }
function Read-State { param($Case,[string]$Id) & $getStatePath -DispatchId $Id -ConfigPath $Case.Config }
function Assert-PublicOutput { param($Value,[string]$Publication)
 Assert-Equal ($Value.PSObject.Properties.Name) @('version','dispatchId','revision','phase','status','projectRepository','report','question','context','options','diagnostic','issuePublication','issueNumber','issueUrl','projectionDiagnostic') 'public output order'
 foreach($forbidden in @('Task','Answer','ThreadId','localPath','project','token','credential')) { Assert-True ($Value.PSObject.Properties.Name -notcontains $forbidden) "public output excludes $forbidden" }
 Assert-Equal $Value.issuePublication $Publication 'issue publication enum'
}

$root=Join-Path ([IO.Path]::GetTempPath()) ('resume-orchestrator-'+[guid]::NewGuid().ToString('N'));[void](New-Item -ItemType Directory $root);$saved=Get-CodexDispatchOrchestratorCredentialSnapshot
try {
 Remove-CodexDispatchOrchestratorCredentials
 # 1-10 input and state admission
 Assert-Throws { Assert-ResumeInput -DispatchId bad -Answer x -IssueNumber 42 } 'error:' 'invalid DispatchId'; Pass 'DispatchId rejected'
 Assert-Throws { Assert-ResumeInput -DispatchId '11111111-1111-1111-1111-111111111111' -Answer '' -IssueNumber 42 } 'error:' 'empty Answer'; Pass 'empty Answer rejected'
 Assert-Throws { Assert-ResumeInput -DispatchId '11111111-1111-1111-1111-111111111111' -Answer '   ' -IssueNumber 42 } 'error:' 'whitespace Answer'; Pass 'whitespace Answer rejected'
 Assert-Throws { Assert-ResumeInput -DispatchId '11111111-1111-1111-1111-111111111111' -Answer ('x'*16385) -IssueNumber 42 } 'error:' 'long Answer'; Pass 'long Answer rejected'
 Assert-Throws { Assert-ResumeInput -DispatchId '11111111-1111-1111-1111-111111111111' -Answer x -IssueNumber 0 } 'error:' 'invalid Issue'; Pass 'Issue rejected'
 $case=New-Case $root 'valid';$state=New-ResumeState $case;$fx=New-Fixture $case; $r=Invoke-Resume $case $fx $state;Assert-Equal $r.status completed 'completed';Pass 'happy completed'
 Assert-Equal $fx.Context.WorkerRequest.Answer ' answer ' 'answer exact';Pass 'Answer preserved'
 Assert-Equal $fx.Context.WorkerRequest.ProjectRepository 'owner/project' 'state repository';Pass 'state repository authority'
 Assert-Equal $fx.Context.WorkerRequest.ThreadId $state.threadId 'state thread';Pass 'state thread authority'
 Assert-Equal ($fx.Context.WorkerRequest.Keys) @('Answer','ProjectRepository','ThreadId','ConfigPath','IndexPath') 'exact Worker request keys';Pass 'exact Worker request contract'
 Assert-Equal $fx.Context.WorkerRequest.IndexPath ([IO.Path]::GetFullPath((Join-Path $case.Root 'project-index.json'))) 'resolved IndexPath';Pass 'Worker receives resolved current-CWD IndexPath'
 Assert-True ($fx.Context.WorkerRequest.Keys -notcontains 'Task') 'Worker has no Task';Pass 'Worker request excludes execution injection'
 Assert-True (-not $fx.Context.WorkerEnv.Contains('CODEX_DISPATCH_GITHUB_TOKEN')) 'worker credential absent';Pass 'credential absent worker'
 Assert-Equal $fx.Context.WorkerState.status running 'running before worker';Pass 'state write before worker'
 Assert-Equal $fx.Context.WorkerState.report '' 'fields cleared';Pass 'output fields cleared'
 Assert-Equal $r.projectRepository 'owner/project' 'worker project ignored';Pass 'worker project cannot overwrite state'
 Assert-Equal $r.issuePublication updated 'updated success';Pass 'updated publication success'
 Assert-Equal ($fx.Context.PublisherRequest.Keys) @('DispatchId','IssueNumber','ConfigPath') 'exact Publisher request keys';Pass 'exact Publisher request contract'
 Assert-Equal $fx.Context.PublisherRequest.IssueNumber 42 'Publisher IssueNumber supplied';Pass 'Publisher gets supplied IssueNumber'
 Assert-PublicOutput $r updated;Pass 'completed public output contract'
 $case=New-Case $root 'answer-boundary';$state=New-ResumeState $case;$fx=New-Fixture $case;$answerBoundary='x'*16384;$r=Invoke-Resume $case $fx $state -Answer $answerBoundary;Assert-Equal $fx.Context.WorkerRequest.Answer $answerBoundary 'Answer boundary exact';Pass 'Answer length 16384 passes unchanged'
 # 11-20 result mapping / publisher
 foreach($mode in @('needs_input','failed')){$case=New-Case $root $mode;$state=New-ResumeState $case;$fx=New-Fixture $case -Mode $mode;$r=Invoke-Resume $case $fx $state;Assert-Equal $r.status $mode $mode;Pass "worker $mode mapping";Assert-PublicOutput $r updated;Pass "$mode public output contract"}
 $case=New-Case $root 'noop';$state=New-ResumeState $case;$fx=New-Fixture $case -Publish noop;$r=Invoke-Resume $case $fx $state;Assert-Equal $r.issuePublication noop 'noop';Pass 'noop publication success'
 foreach($p in @('created','unknown','throw','wrongdispatch','wrongrevision','wrongissue')){$case=New-Case $root $p;$state=New-ResumeState $case;$fx=New-Fixture $case -Publish $p;$r=Invoke-Resume $case $fx $state;Assert-Equal $r.issuePublication failed 'projection failed';Assert-Equal $r.issueNumber $null 'projection no issue number';Assert-Equal $r.issueUrl $null 'projection no issue url';Assert-True (-not [string]::IsNullOrWhiteSpace($r.projectionDiagnostic)) 'projection diagnostic';Assert-Equal (Read-State $case $state.dispatchId).status completed 'state preserved';Assert-PublicOutput $r failed;Pass "invalid projection $p"}
 # 21-30 strict failures, updates and nonresumable
 foreach($m in @('throw','malformed','nullfailed','wrongthread')){$case=New-Case $root $m;$state=New-ResumeState $case;$fx=New-Fixture $case -Mode $m;$r=Invoke-Resume $case $fx $state;Assert-Equal $r.status failed 'failure maps';Assert-Equal (Read-State $case $state.dispatchId).threadId $state.threadId 'thread preserved';Pass "strict worker failure $m"}
 $case=New-Case $root 'privacy-throw';$state=New-ResumeState $case;$fx=New-Fixture $case -Mode throw;$answer='ANSWER-SECRET-6C2A';[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN','CREDENTIAL-SECRET-6C2A',[EnvironmentVariableTarget]::Process);try{$r=Invoke-Resume $case $fx $state -Answer $answer}finally{[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$null,[EnvironmentVariableTarget]::Process)};$durable=Read-State $case $state.dispatchId;Assert-Equal $durable.status failed 'throw durable failed';Assert-Equal $durable.projectRepository 'owner/project' 'throw repository preserved';Assert-Equal $durable.threadId $state.threadId 'throw thread preserved';foreach($marker in @($answer,'C:\private\secret.txt',$state.threadId,'22222222-2222-2222-2222-222222222222','CREDENTIAL-SECRET-6C2A')){Assert-True (-not $durable.diagnostic.Contains($marker)) 'durable throw privacy';Assert-True (-not $r.diagnostic.Contains($marker)) 'public throw privacy'};Assert-True ($durable.diagnostic.Length -gt 0 -and $durable.diagnostic.Length -le 2048) 'bounded throw diagnostic';Pass 'Worker throw diagnostic privacy'
 $case=New-Case $root 'privacy-structured';$state=New-ResumeState $case;$fx=New-Fixture $case -Mode secretfailed;$r=Invoke-Resume $case $fx $state;$durable=Read-State $case $state.dispatchId;foreach($marker in @('STRUCTURED-SECRET-6C2A','C:\private\secret.txt','22222222-2222-2222-2222-222222222222')){Assert-True (-not $durable.diagnostic.Contains($marker)) 'durable structured privacy';Assert-True (-not $r.diagnostic.Contains($marker)) 'public structured privacy'};Pass 'structured failed diagnostic privacy'
 $case=New-Case $root 'privacy-projection';$state=New-ResumeState $case;$fx=New-Fixture $case -Publish throw;[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN','CREDENTIAL-SECRET-6C2A',[EnvironmentVariableTarget]::Process);try{$r=Invoke-Resume $case $fx $state}finally{[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$null,[EnvironmentVariableTarget]::Process)};$durable=Read-State $case $state.dispatchId;Assert-Equal $r.issuePublication failed 'projection privacy failure';foreach($marker in @('PROJECTION-SECRET-6C2A','C:\private\secret.txt','22222222-2222-2222-2222-222222222222','CREDENTIAL-SECRET-6C2A')){Assert-True (-not $r.projectionDiagnostic.Contains($marker)) 'projection diagnostic privacy'};Assert-Equal $durable.status completed 'projection preserves durable execution';Pass 'projection diagnostic privacy'
 $case=New-Case $root 'running-readback';$state=New-ResumeState $case;$fx=New-Fixture $case;$r=Invoke-Resume $case $fx $state;$before=$fx.Context.WorkerState;Assert-Equal $before.revision ([int64]$state.revision+1) 'running revision';Assert-Equal $before.phase worker 'running phase';Assert-Equal $before.status running 'running status';Assert-Equal $before.projectRepository $state.projectRepository 'running repository';Assert-Equal $before.threadId $state.threadId 'running thread';Assert-Equal $before.report '' 'running report';Assert-Equal $before.question '' 'running question';Assert-Equal $before.context '' 'running context';Assert-Equal @($before.options).Count 0 'running options';Assert-Equal $before.diagnostic '' 'running diagnostic';Pass 'complete running State readback'
 $environmentBefore=Get-CodexDispatchOrchestratorCredentialSnapshot;[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN','DEDICATED-TOKEN-6C2A',[EnvironmentVariableTarget]::Process);Set-CodexDispatchOrchestratorEmptyEnvironmentVariable -Name 'GH_TOKEN';[Environment]::SetEnvironmentVariable('GITHUB_TOKEN','GENERAL-TOKEN-6C2A',[EnvironmentVariableTarget]::Process);try{$case=New-Case $root 'credential-full';$state=New-ResumeState $case;$fx=New-Fixture $case;$r=Invoke-Resume $case $fx $state;foreach($name in @('CODEX_DISPATCH_GITHUB_TOKEN','GH_TOKEN','GITHUB_TOKEN')){Assert-True (-not $fx.Context.WorkerEnv.Contains($name)) 'Worker credential absent'};Assert-Equal $fx.Context.PublisherEnv['CODEX_DISPATCH_GITHUB_TOKEN'] 'DEDICATED-TOKEN-6C2A' 'Publisher dedicated token';Assert-True (-not $fx.Context.PublisherEnv.Contains('GH_TOKEN')) 'Publisher GH absent';Assert-True (-not $fx.Context.PublisherEnv.Contains('GITHUB_TOKEN')) 'Publisher GITHUB absent';Assert-Equal ([Environment]::GetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',[EnvironmentVariableTarget]::Process)) 'DEDICATED-TOKEN-6C2A' 'dedicated restored';Assert-True ([Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::Process).Contains('GH_TOKEN')) 'empty GH restored as present';Assert-Equal ([Environment]::GetEnvironmentVariable('GH_TOKEN',[EnvironmentVariableTarget]::Process)) '' 'empty GH exact';Assert-Equal ([Environment]::GetEnvironmentVariable('GITHUB_TOKEN',[EnvironmentVariableTarget]::Process)) 'GENERAL-TOKEN-6C2A' 'GITHUB restored';Pass 'credential isolation and exact restoration'}finally{Restore-CodexDispatchOrchestratorCredentials -Snapshot $environmentBefore}
 $environmentBefore=Get-CodexDispatchOrchestratorCredentialSnapshot;[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$null,[EnvironmentVariableTarget]::Process);Set-CodexDispatchOrchestratorEmptyEnvironmentVariable -Name 'GH_TOKEN';[Environment]::SetEnvironmentVariable('GITHUB_TOKEN','WORKER-THROW-TOKEN',[EnvironmentVariableTarget]::Process);$expected=Get-CodexDispatchOrchestratorCredentialSnapshot;try{$case=New-Case $root 'credential-worker-throw';$state=New-ResumeState $case;$fx=New-Fixture $case -Mode throw;$r=Invoke-Resume $case $fx $state;foreach($name in @('CODEX_DISPATCH_GITHUB_TOKEN','GH_TOKEN','GITHUB_TOKEN')){Assert-True (-not $fx.Context.WorkerEnv.Contains($name)) 'Worker throw credential absent'};Assert-EnvironmentSnapshot $expected 'Worker throw restore';Pass 'credential restoration Worker throw'}finally{Restore-CodexDispatchOrchestratorCredentials -Snapshot $environmentBefore}
 $environmentBefore=Get-CodexDispatchOrchestratorCredentialSnapshot;[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN','PUBLISHER-THROW-TOKEN',[EnvironmentVariableTarget]::Process);Set-CodexDispatchOrchestratorEmptyEnvironmentVariable -Name 'GH_TOKEN';[Environment]::SetEnvironmentVariable('GITHUB_TOKEN',$null,[EnvironmentVariableTarget]::Process);$expected=Get-CodexDispatchOrchestratorCredentialSnapshot;try{$case=New-Case $root 'credential-publisher-throw';$state=New-ResumeState $case;$fx=New-Fixture $case -Publish throw;$r=Invoke-Resume $case $fx $state;Assert-Equal $fx.Context.PublisherEnv['CODEX_DISPATCH_GITHUB_TOKEN'] 'PUBLISHER-THROW-TOKEN' 'Publisher throw dedicated token';Assert-True (-not $fx.Context.PublisherEnv.Contains('GH_TOKEN')) 'Publisher throw GH absent';Assert-True (-not $fx.Context.PublisherEnv.Contains('GITHUB_TOKEN')) 'Publisher throw GITHUB absent';Assert-EnvironmentSnapshot $expected 'Publisher throw restore';Pass 'credential restoration Publisher throw'}finally{Restore-CodexDispatchOrchestratorCredentials -Snapshot $environmentBefore}
 $case=New-Case $root 'conflict';$state=New-ResumeState $case;$fx=New-Fixture $case;$fx.Context.FailUpdate=1;Assert-Throws {Invoke-Resume $case $fx $state} 'state failure' 'initial state failure';Assert-Equal $fx.Context.WorkerCalls 0 'no worker';Pass 'state write failure before worker'
 $case=New-Case $root 'finalfail';$state=New-ResumeState $case;$fx=New-Fixture $case;$fx.Context.FailUpdate=2;Assert-Throws {Invoke-Resume $case $fx $state} 'state failure' 'final failure';Assert-Equal $fx.Context.PublisherCalls 0 'no pub';Pass 'state write failure after worker'
 foreach($s in @('routing/pending','routing/running','routing/needs_input','worker/running','worker/completed','worker/failed')){ $case=New-Case $root ($s.Replace('/','-'));$st=& $newStatePath -Task t -ConfigPath $case.Config;if($s -ne 'routing/pending'){ $a=$s.Split('/');if($s -eq 'routing/running'){& $updateStatePath -DispatchId $st.dispatchId -ExpectedRevision $st.revision -Phase routing -Status running -ConfigPath $case.Config|Out-Null}elseif($s -eq 'routing/needs_input'){& $updateStatePath -DispatchId $st.dispatchId -ExpectedRevision $st.revision -Phase routing -Status needs_input -Report r -Question q -Context c -Options @('A','B') -ConfigPath $case.Config|Out-Null}else{& $updateStatePath -DispatchId $st.dispatchId -ExpectedRevision $st.revision -Phase routing -Status running -ConfigPath $case.Config|Out-Null;$x=Read-State $case $st.dispatchId;& $updateStatePath -DispatchId $st.dispatchId -ExpectedRevision $x.revision -Phase worker -Status running -ProjectRepository owner/project -ConfigPath $case.Config|Out-Null;$x=Read-State $case $st.dispatchId;if($s -ne 'worker/running'){& $updateStatePath -DispatchId $st.dispatchId -ExpectedRevision $x.revision -Phase worker -Status $a[1] -ProjectRepository owner/project -ThreadId '11111111-1111-1111-1111-111111111111' -Report $(if($a[1]-eq'completed'){'r'}else{''}) -Diagnostic $(if($a[1]-eq'failed'){'d'}else{''}) -ConfigPath $case.Config|Out-Null}}};$st=Read-State $case $st.dispatchId;$fx=New-Fixture $case;Assert-Throws {Invoke-Resume $case $fx $st} 'error:' 'non resumable';Assert-Equal $fx.Context.WorkerCalls 0 'no worker';Pass "nonresumable $s" }
 # 31-50 public/output/privacy/credentials
 $case=New-Case $root 'order';$state=New-ResumeState $case;$fx=New-Fixture $case;$r=Invoke-Resume $case $fx $state;Assert-Equal ($r.PSObject.Properties.Name) @('version','dispatchId','revision','phase','status','projectRepository','report','question','context','options','diagnostic','issuePublication','issueNumber','issueUrl','projectionDiagnostic') 'order';Pass 'output order'
 Assert-True ($r.PSObject.Properties.Name -notcontains 'threadId') 'no thread';Pass 'output privacy fields'
 $case=New-Case $root 'missing';$fx=New-Fixture $case;Push-Location $case.Root;try{try{Invoke-CodexDispatchResumeOrchestratorInternal -DispatchId '33333333-3333-3333-3333-333333333333' -Answer secret -IssueNumber 42 -ConfigPath $case.Config -Dependencies $fx.Dependencies;throw 'none'}catch{Assert-True (-not $_.Exception.Message.Contains($case.Root)) 'no path'}}finally{Pop-Location};Pass 'missing State internal is caught by public wrapper design'
 $tokens=$null;$parseErrors=$null;$ast=[System.Management.Automation.Language.Parser]::ParseFile($publicPath,[ref]$tokens,[ref]$parseErrors);Assert-Equal $parseErrors.Count 0 'public AST parse';Assert-Equal @($ast.ParamBlock.Parameters | ForEach-Object {$_.Name.VariablePath.UserPath}) @('DispatchId','Answer','IssueNumber','ConfigPath') 'exact public AST parameter order';Pass 'public AST exact parameter contract'
 $secretAnswer='ANSWER-SECRET-6C2A';$secretCredential='CREDENTIAL-SECRET-6C2A';$old=[Environment]::GetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',[EnvironmentVariableTarget]::Process);[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$secretCredential,[EnvironmentVariableTarget]::Process);try{Push-Location $case.Root;try{$caught=$null;try{& $publicPath -DispatchId '33333333-3333-3333-3333-333333333333' -Answer $secretAnswer -IssueNumber 42}catch{$caught=$_.Exception.Message};Assert-True ($null -ne $caught) 'public missing State throws';foreach($secret in @($secretAnswer,$secretCredential,$case.Root,'33333333-3333-3333-3333-333333333333')){Assert-True (-not $caught.Contains($secret)) 'public error hides sensitive value'}}finally{Pop-Location}}finally{[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$old,[EnvironmentVariableTarget]::Process)};Pass 'public wrapper missing-State privacy'
 $fixtureRoot=Join-Path $root 'nested-common-missing';[void](New-Item -ItemType Directory -Path $fixtureRoot);Copy-Item -LiteralPath $publicPath -Destination (Join-Path $fixtureRoot 'Invoke-CodexDispatchResume.ps1');Copy-Item -LiteralPath (Join-Path $scriptsRoot 'CodexDispatchResumeOrchestrator.Common.ps1') -Destination (Join-Path $fixtureRoot 'CodexDispatchResumeOrchestrator.Common.ps1');$fixturePublic=Join-Path $fixtureRoot 'Invoke-CodexDispatchResume.ps1';$nestedAnswer='NESTED-ANSWER-SECRET';$nestedCredential='NESTED-CREDENTIAL-SECRET';$old=[Environment]::GetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',[EnvironmentVariableTarget]::Process);[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$nestedCredential,[EnvironmentVariableTarget]::Process);try{$caught=$null;try{& $fixturePublic -DispatchId '33333333-3333-3333-3333-333333333333' -Answer $nestedAnswer -IssueNumber 42}catch{$caught=$_.Exception.Message};Assert-True ($null -ne $caught) 'nested common failure throws';Assert-Equal $caught 'Codex Dispatch Resume Orchestrator error: execution failed.' 'nested common fixed public error';foreach($secret in @($nestedAnswer,$nestedCredential,$fixtureRoot,'33333333-3333-3333-3333-333333333333','CodexDispatchOrchestrator.Common.ps1')){Assert-True (-not $caught.Contains($secret)) 'nested common error privacy'}}finally{[Environment]::SetEnvironmentVariable('CODEX_DISPATCH_GITHUB_TOKEN',$old,[EnvironmentVariableTarget]::Process)};Pass 'public nested-common initialization privacy'
 Assert-True (([IO.File]::ReadAllText($publicPath)) -notmatch '\[string\]\$ProjectRepository|\[string\]\$ThreadId|\[string\]\$IndexPath') 'no public authority parameters';Pass 'public AST no fifth authority parameter'
 $commonText=[IO.File]::ReadAllText((Join-Path $scriptsRoot 'CodexDispatchResumeOrchestrator.Common.ps1'))
 $publicText=[IO.File]::ReadAllText((Join-Path $scriptsRoot 'Invoke-CodexDispatchResume.ps1'))
 foreach($check in @(
  @{Name='public DispatchId';Text=$publicText;Need='[string]$DispatchId'},
  @{Name='public Answer';Text=$publicText;Need='[string]$Answer'},
  @{Name='public IssueNumber';Text=$publicText;Need='[Int64]$IssueNumber'},
  @{Name='no ProjectRepository public';Text=$publicText;Need='ProjectRepository';Absent=$true},
  @{Name='no ThreadId public';Text=$publicText;Need='ThreadId';Absent=$true},
  @{Name='no IndexPath public';Text=$publicText;Need='IndexPath';Absent=$true},
  @{Name='publisher receives IssueNumber';Text=$commonText;Need='IssueNumber=$IssueNumber'},
  @{Name='publisher success updated';Text=$commonText;Need="@('updated','noop')"},
  @{Name='no publisher create';Text=$commonText;Need="action -cnotin @('updated','noop')"},
  @{Name='state output source';Text=$commonText;Need='New-CodexDispatchOrchestratorOutput'},
  @{Name='no Worker Task';Text=$commonText;Need='Answer=$Answer;ProjectRepository=$repo;ThreadId=$thread'},
  @{Name='index once';Text=$commonText;Need='$indexPath=Get-CodexDispatchOrchestratorIndexPath'},
  @{Name='credentials stripped';Text=$commonText;Need='Remove-CodexDispatchOrchestratorCredentials'},
  @{Name='credentials restored';Text=$commonText;Need='Restore-CodexDispatchOrchestratorCredentials'},
  @{Name='running clear fields';Text=$commonText;Need="Report='';Question='';Context='';Options=[string[]]@();Diagnostic=''"},
  @{Name='strict thread equality';Text=$commonText;Need='threadId must exactly equal State threadId'},
  @{Name='no discovery';Text=$commonText;Need='Discover-CodexProjects';Absent=$true},
  @{Name='no index builder';Text=$commonText;Need='Build-CodexProjectIndex';Absent=$true}
 )){$found=$check.Text.Contains($check.Need);if($check.ContainsKey('Absent')){$found=-not $found};Assert-True $found $check.Name;Pass $check.Name}
} finally { Restore-CodexDispatchOrchestratorCredentials -Snapshot $saved;Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue }
if($script:passed -ne $testCount){throw "expected $testCount got $script:passed"};Write-Host "ALL PASS $script:passed/$testCount"
